# Generated by Django 2.1.7 on 2019-03-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190329_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос ответ', 'verbose_name_plural': 'Вопрос ответ'},
        ),
        migrations.AlterModelOptions(
            name='howword',
            options={'verbose_name': 'Как мы работаем', 'verbose_name_plural': 'Как мы работаем'},
        ),
        migrations.AlterModelOptions(
            name='trust',
            options={'verbose_name': 'Нам доверяют', 'verbose_name_plural': 'Нам доверяют'},
        ),
        migrations.AlterModelOptions(
            name='violations',
            options={'verbose_name': 'Как мы работаем', 'verbose_name_plural': 'Как мы работаем'},
        ),
    ]
