# Generated by Django 2.1.7 on 2019-03-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190329_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trust',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
