# Generated by Django 2.1.7 on 2019-03-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190329_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('reviews', models.TextField(max_length=1000, verbose_name='Отзыв')),
                ('avatar', models.ImageField(upload_to='img/', verbose_name='Аватарка')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='picture',
            field=models.ImageField(upload_to='img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='asked',
            field=models.TextField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='questions',
            field=models.TextField(max_length=100, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='trust',
            name='picture',
            field=models.ImageField(upload_to='img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='trust',
            name='text',
            field=models.TextField(max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='trust',
            name='titel',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='violations',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
