# Generated by Django 2.1.7 on 2019-03-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_content_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews',
            new_name='review',
        ),
    ]
