# Generated by Django 2.1.7 on 2019-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190331_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.TextField(max_length=1000, verbose_name='О Нас')),
                ('vklink', models.CharField(max_length=50, verbose_name='Вконтакте')),
                ('insta', models.CharField(max_length=50, verbose_name='Инстаграмм')),
                ('number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('strit', models.CharField(max_length=100, verbose_name='Адресс')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
